# Generated by Django 5.2 on 2026-05-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STU', 'Студент'), ('TCH', 'Преподаватель')], default='STU', max_length=3, verbose_name='Роль в системе'),
        ),
        migrations.AlterField(
            model_name='teamrequest',
            name='contact_info',
            field=models.CharField(max_length=255, verbose_name='Contacts'),
        ),
    ]
