# Generated by Django 5.2 on 2026-05-18 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_userprofile_role_alter_teamrequest_contact_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='idea',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_chat', to='ideas.idea', verbose_name='Идея (Групповой чат)'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='group_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Участники чата'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='ideas.teamrequest', verbose_name='Заявка (Личный чат)'),
        ),
    ]
