# Generated by Django 5.2 on 2026-05-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_conversation_idea_conversation_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='idea_covers/', verbose_name='Обложка проекта'),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
